### ISSUE TITLE
Only render the first element within Option

### ISSUE THREAD

**Issue by Aaallan** [iblq/antd-virtual-select#18]
![image](https://user-images.githubusercontent.com/36944529/77388596-74aaff00-6df5-11ea-8cd5-64e50d81aa95.png)
![image](https://user-images.githubusercontent.com/36944529/77388632-88566580-6df5-11ea-8ecd-9277123d3a1c.png)

reproduced link: https://codesandbox.io/s/superselect-s94w8

**Comment by iblq** [comment]
Because I set the height of the Option to be fixed at 32px, I cannot dynamically expand the height for the time being. If you really need it, I can set an 'OptionHeight' props later to allow the height of the Option to be dynamically controlled, but the height of each Option must be the same  @Aaallan

**Comment by Aaallan** [comment]
It will be great to have the 'OptionHeight' control. Thanks

**Comment by Aaallan** [comment]
Hi there, is there any plan to implement this feature recently? Thanks

**Comment by iblq** [comment]
Sorry, just finished
